#56 fix username already exist exception and invalid login exception
hxue98/NewsToday pull request #57
Opened 2020-08-07 20:02 UTC by Joexiaohongchen

2020-08-07 22:53 UTC, hxue98 requested changes

2020-08-07 22:53 UTC, hxue98 commented on backend/build.gradle
> +
Remove empty line

2020-08-07 22:53 UTC, hxue98 commented on backend/src/main/java/team/YongAndJoe/NewsTodayBackend/controller/AccountController.java
> +import org.springframework.web.bind.annotation.*;
Do not use * in import.

2020-08-07 22:53 UTC, hxue98 commented on backend/src/main/java/team/YongAndJoe/NewsTodayBackend/entity/User.java
> +    public String getConfirmpassword() {
Do not need confirm password in backend. Only frontend needs to confirm password before making the request.

2020-08-07 22:53 UTC, hxue98 commented on backend/src/main/java/team/YongAndJoe/NewsTodayBackend/util/AjaxResponseBody.java
> +    private String username;
Remove username

2020-08-07 22:53 UTC, hxue98 commented on backend/src/main/java/team/YongAndJoe/NewsTodayBackend/validator/LoginValidator.java
> +
Remove empty line

2020-08-07 22:53 UTC, hxue98 commented on backend/src/main/java/team/YongAndJoe/NewsTodayBackend/validator/LoginValidator.java
> +        } else if(!accountService.existByUsername(user.getUsername())){
Add check for password length

2020-08-07 22:53 UTC, hxue98 commented on database/.vscode/settings.json
> +    "git.ignoreLimitWarning": true
add .gitignore to database and frontend folder.

2020-08-07 22:55 UTC, hxue98 requested changes

2020-08-07 22:55 UTC, hxue98 commented on backend/src/main/java/team/YongAndJoe/NewsTodayBackend/controller/AccountController.java
> +//        body.setJwtToken(jwtTokenUtil.generateJwt(user));
Uncomment this line

2020-08-07 23:46 UTC, Joexiaohongchen commented
All updated, please review.

2020-08-08 00:33 UTC, hxue98 approved these changes

2020-08-08 00:34 UTC, merged